### ISSUE TITLE
Can't figure out how to setup smartcov_paths_hook

### ISSUE THREAD

**Issue by scherrey** [carljm/pytest-smartcov#1]
In my pytest.ini I have the following line:

``` bash
smartcov_paths_hook=utils.tests.smartcov.cov_source_for_test_paths
```

My project directory structure is ~/projects/wfp/dev/backend-survey-service/survey_service
This is where I run py.test from and also where pytest.ini resides.

Under the survey_service directory I have a bunch of app dirs including utils/tests/smartcov.py which contains:

``` python

# -*- coding: utf-8 -*-
def cov_source_for_test_paths(paths=None):
    """
    This is required for pytest-smartcov to determine what paths should have
    coverage measured for them.
    """
    if not paths:
        return ['.', ]
    else:
        return path

```

I'm not sure if this code is correct or not. It's hard to find examples. Is it really necessary to write a python method to determine what modules will have code coverage performed? Anyway - I have a bigger problem...

Everything is being built on Kubuntu 14.10 with 3.16.0-31-generic linux kernel Python 3.4.2

Running py.test I get the following results:

```
bmf1000@redsky:/backend-survey-service/survey_service$ py.test 
Traceback (most recent call last):
  File "/usr/local/bin/py.test", line 9, in <module>
    load_entry_point('pytest==2.7.0', 'console_scripts', 'py.test')()
  File "/usr/local/lib/python3.4/dist-packages/_pytest/config.py", line 32, in main
    config = _prepareconfig(args, plugins)
  File "/usr/local/lib/python3.4/dist-packages/_pytest/config.py", line 85, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/usr/local/lib/python3.4/dist-packages/_pytest/core.py", line 521, in __call__
    return self._docall(self.methods, kwargs)
  File "/usr/local/lib/python3.4/dist-packages/_pytest/core.py", line 528, in _docall
    firstresult=self.firstresult).execute()
  File "/usr/local/lib/python3.4/dist-packages/_pytest/core.py", line 393, in execute
    return wrapped_call(method(*args), self.execute)
  File "/usr/local/lib/python3.4/dist-packages/_pytest/core.py", line 109, in wrapped_call
    wrap_controller.send(call_outcome)
  File "/usr/local/lib/python3.4/dist-packages/_pytest/helpconfig.py", line 28, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/usr/local/lib/python3.4/dist-packages/_pytest/core.py", line 137, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.4/dist-packages/_pytest/core.py", line 123, in __init__
    self.result = func()
  File "/usr/local/lib/python3.4/dist-packages/_pytest/core.py", line 394, in execute
    res = method(*args)
  File "/usr/local/lib/python3.4/dist-packages/_pytest/config.py", line 636, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/local/lib/python3.4/dist-packages/_pytest/config.py", line 746, in parse
    self._preparse(args)
  File "/usr/local/lib/python3.4/dist-packages/_pytest/config.py", line 718, in _preparse
    args=args, parser=self._parser)
  File "/usr/local/lib/python3.4/dist-packages/_pytest/core.py", line 521, in __call__
    return self._docall(self.methods, kwargs)
  File "/usr/local/lib/python3.4/dist-packages/_pytest/core.py", line 528, in _docall
    firstresult=self.firstresult).execute()
  File "/usr/local/lib/python3.4/dist-packages/_pytest/core.py", line 393, in execute
    return wrapped_call(method(*args), self.execute)
  File "/usr/local/lib/python3.4/dist-packages/_pytest/core.py", line 113, in wrapped_call
    return call_outcome.get_result()
  File "/usr/local/lib/python3.4/dist-packages/_pytest/core.py", line 137, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.4/dist-packages/_pytest/core.py", line 123, in __init__
    self.result = func()
  File "/usr/local/lib/python3.4/dist-packages/_pytest/core.py", line 394, in execute
    res = method(*args)
  File "/usr/local/lib/python3.4/dist-packages/smartcov.py", line 22, in pytest_load_initial_conftests
    early_config.inicfg.get('smartcov_paths_hook', ''))
  File "/usr/local/lib/python3.4/dist-packages/smartcov.py", line 39, in _get_paths_hook
    module = import_module(module_path)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2189, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2189, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2201, in _find_and_load_unlocked
ImportError: No module named 'utils'
```

So no idea why it can't file the utils directory. Anything I can do to get my code coverage working? 

Here's an ipython session that demonstrates that I can access the function just fine:

``` python
bmf1000@redsky:/backend-survey-service/survey_service$ python3 manage.py shell --settings=survey_service.settings.local
Python 3.4.0 (default, Apr 11 2014, 13:05:11) 
Type "copyright", "credits" or "license" for more information.

IPython 3.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from utils.tests.smartcov import cov_source_for_test_paths

In [2]: cov_source_for_test_paths()
Out[2]: ['.']
```

**Comment by carljm** [comment]
Hi Ben! Thanks for the inquiry, and sorry for the lack of detailed documentation. I built this for my own needs and wasn't sure if it would even interest anyone else; so far you're the first person to inquire about it :-)

The reason pytest-smartcov requires a Python function to determine which files should have coverage measured on them is that its whole purpose is to enable arbitrary "mappings" from "test files run" to "Python files that I expect those tests to exercise." The idea is that my test files are structured to mirror my production code, so if I have a file "mypackage/foo/bar.py" in my production code I will have a file "tests/foo/test_bar.py" in my tests, and when I run `py.test tests/foo/test_bar.py` I want to see a coverage report that only covers "mypackage/foo/bar.py", not the rest of my code. So in that case I write a paths-hook function like this:

```
def cov_source_for_test_paths(paths):
    """Given test paths, return the source paths on which to measure coverage.

    If no specific test paths were given, measure coverage on entire Python
    code tree.

    """
    if not paths:
        return ['mypackage']
    return [_code_path(p) for p in paths]


def _code_path(path):
    """Return the code path corresponding to a given test path."""
    return path.replace('tests/', 'mypackage/').replace('test_', '')
```

If that feature doesn't interest you, then you may be better off with https://pypi.python.org/pypi/pytest-cov (a much older and more widely-used integration of pytest with coverage), since that feature is really the main selling point for pytest-smartcov. (Though it also does some nice stuff that pytest-cov doesn't in the terminal output; highlighting only the uncovered code and keeping the report very short - one line - if everything is covered.)

So - assuming you actually want to use pytest-smartcov, let's see about the details of your problem...

I think in your paths-hook function, the empty case should work OK (I'm not sure if coverage handles `.` or not, I usually use the name of my top-level Python module; or you could return a list of all of them if you have more than one). The `else` case doesn't seem right, as the incoming paths are _test_ file paths, and you need to transform them into the paths to the corresponding production-code files.

The import problem is probably quite simple. When you run a script like `manage.py` Python automatically puts that script's directory on `sys.path`, so all your imports work. When you run `py.test` that doesn't happen (because the `py.test` script is off in some other directory). What I'm not sure of is how your imports are working in your tests; something else must be putting your top-level directory on `sys.path`, but I'm not sure what is doing it. Whatever it is, it must be happening after the `pytest-smartcov` hooks.

On my projects, I solve this problem be ensuring that my project is always on `sys.path`; I give it a very simple `setup.py` file and run `pip install -e .` which installs the project into my virtualenv in "editable" mode (meaning the files aren't copied elsewhere, the current directory is just linked into the virtualenv's `sys.path`).

Hope that's helpful!

**Comment by carljm** [comment]
Closing due to lack of response.
